### ISSUE TITLE
 AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by BraveAction** [googlesamples/android-testing#126]
java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
at com.yuerbao.index.scores.AccumulateScoresActivity.onCreate(AccumulateScoresActivity.java:23)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5835)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuerbao/com.yuerbao.index.scores.AccumulateScoresActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5835)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
at com.yuerbao.index.scores.AccumulateScoresActivity.onCreate(AccumulateScoresActivity.java:23)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
... 10 more

Test running failed: Instrumentation run failed due to 'java.lang.IllegalArgumentException'

**Comment by JoseAlcerreca** [comment]
Compiles and runs fine here. Can you provide more details? Closing for now.

**Comment by BrianLusina** [comment]
Getting the same issue when running with Build tools version 25.0.0 and Android Studio 3.0 Preview Canary 5.

``` plain
java.lang.RuntimeException: Unable to start activity ComponentInfo{com......MainActivity}: 
java.lang.IllegalArgumentException: 
AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }

```

This is the theme being used:

``` xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar"/>

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light"/>

</resources>

```
> This has happened even after cleaning the project and rebuilding 

Kindly advice, nothing I am doing is working

**Comment by vpratfr** [comment]
Same error here with latest AS canary.

Single activity, app theme set to the overriden theme, theme as follows:

    <style name="Theme.Example" parent="Theme.AppCompat.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

**Comment by rocky58** [comment]
Also me same error... AS canary 5 and AS canary 4
I don't know what must do... ten days without success!!!! Sigh sigh sigh...

**Comment by JoseAlcerreca** [comment]
We only support stable releases of AS and since this is not related to testing in any way, it won't be fixed until 3.0 is stable. However, we gladly accept PRs as we can bump the supportlib version without moving to canary. Thanks!

**Comment by vpratfr** [comment]
As I am early in my devs, I have currently worked around this by inheriting from FragmentActivity instead of AppCompatActivity.

From googling around, looks like it may be a bug in the android gradle plugin.

**Comment by BrianLusina** [comment]
@vpratfr Seems so, let me try that too, it is strange that it does that, waiting on a stable release of the plugin.

**Comment by rocky58** [comment]
Finallyyyyyyyy... ok a canary version but this type of error is very frustrating!!!

**Comment by vpratfr** [comment]
Works now on AS canary 6

**Comment by BrianLusina** [comment]
Finally a fix, now we can move forward. It's kind of a relief to know that I was not the only one suffering from this issue :smile:

**Comment by Mostafayehya** [comment]
@BrianLusina  , how did you fix it ?
