### ISSUE TITLE
Unable to compile BasicSampleBundled

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-testing#133]
I am trying to build the BasicSampleBundled project in Android Studio 3.0 Canary 4.  I get the following compilation error:
> Error:Error converting bytecode to dex:
Cause: invokedynamic not supported
Error:com.android.dx.cf.code.SimException: invokedynamic not supported
Error:	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Error:	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Error:	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Error:	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Error:	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
Error:	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
Error:	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
Error:	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
Error:	at com.android.builder.dexing.DexArchiveBuilder.processOutputs(DexArchiveBuilder.java:110)
Error:	at com.android.builder.dexing.DexArchiveBuilder.convert(DexArchiveBuilder.java:91)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.lambda$cacheMissAction$0(DexArchiveBuilderTransformCallable.java:236)
Error:	at com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:260)
Error:	at com.android.builder.utils.FileCache.lambda$null$5(FileCache.java:443)
Error:	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
Error:	at com.android.builder.utils.SynchronizedFile.write(SynchronizedFile.java:232)
Error:	at com.android.builder.utils.FileCache.lambda$queryCacheEntry$6(FileCache.java:415)
Error:	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
Error:	at com.android.builder.utils.SynchronizedFile.read(SynchronizedFile.java:215)
Error:	at com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:391)
Error:	at com.android.builder.utils.FileCache.createFile(FileCache.java:273)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:185)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:147)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:53)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Caused by: com.android.dx.cf.code.SimException: invokedynamic not supported
Error:	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:810)
Error:	at com.android.dx.cf.code.BytecodeArray.processWorkSet(BytecodeArray.java:162)
Error:	at com.android.dx.cf.code.BasicBlocker.doit(BasicBlocker.java:346)
Error:	at com.android.dx.cf.code.BasicBlocker.identifyBlocks(BasicBlocker.java:81)
Error:	at com.android.dx.cf.code.Ropper.<init>(Ropper.java:380)
Error:	at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
Error:	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:285)
Error:	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:141)
Error:	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:95)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.translateClass(DexArchiveBuilderCallable.java:93)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:74)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:43)
Error:	... 5 more
Error:Caused by: com.android.dx.cf.iface.ParseException: invokedynamic not supported
Error:	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:777)
Error:	... 16 more
Error:...at bytecode offset 0000000e
Error:...while working on method toImmutableSetMultimap:(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
Error:...while processing toImmutableSetMultimap (Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
Error:...while processing com/google/common/collect/ImmutableSetMultimap.class
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
Error:com.android.dx.cf.code.SimException: invokedynamic not supported
Error:com.android.dx.cf.iface.ParseException: invokedynamic not supported

**Comment by IgorGanapolsky** [comment]
I see, this sample is intended for Eclipse IDE.
