### ISSUE TITLE
Ui Automator -> UiObject2.setText() fails on APK <= 19 if the current TextBox is empty

### ISSUE THREAD

**Issue by marcosdiez** [googlesamples/android-testing#21]
On Android APK <= 19, UiAutomator up to 2.1.0 fails with the when

UiObject2 txtField = getEditTextByAnyMeans();
txtField.setText("blah");

the reason is quite simple ( UiObject2.java:589 ):

    public void setText(String text) {
        AccessibilityNodeInfo node = getAccessibilityNodeInfo();
        /* a lot of stuff */
            CharSequence currentText = node.getText();
            if (!currentText.equals(text)) {

node.getText() is returning null and that is causing the app to crash.

bellow is the stacktrace:

java.lang.NullPointerException
at android.support.test.uiautomator.UiObject2.setText(UiObject2.java:589)
at com.connvision.farmforce.tests.ApplicationTest.setFieldValue(ApplicationTest.java:150)
at com.connvision.farmforce.tests.ApplicationTest.testAddFarmer(ApplicationTest.java:129)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1741)

**Comment by otw** [comment]
Thanks for reporting this! This seems to be an issue in UIAutomator itself. I'll look into it and hopefully we can fix it asap. I'm also closing this issue here as it is unrelated to the actual samples.

**Comment by otw** [comment]
Just t give you a heads up, this bug was already fixed internally and will be in the next release of the support library.

**Comment by maloubobola** [comment]
I encouter the same problem, but I can go throw by setting and empty hint. Something like 
```
    <EditText
        android:id="@+id/password_input"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="text"
        android:hint="" />
```

But even with a default hint, this is not working with an ```inputType``` set to ```textPassword```. Here is the stack trace. I don't know if you also fix this one internally.

```
    java.lang.NullPointerException
        at android.support.test.uiautomator.UiObject2.setText(UiObject2.java:601)
        at com.zenika.aic.demo.login.LoginTestCase.loginSuccess(LoginTestCase.java:151)
        at com.zenika.aic.demo.login.LoginTestCase.testUS4(LoginTestCase.java:80)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


```

**Comment by yuypa** [comment]
On Android APK <= 19, UiAutomator up to 2.1.2 fails with the when
UiObject2 txtField = getEditTextByAnyMeans();
txtField.setText("blah");

the reason is quite simple ( UiObject2.java:601 ):

        CharSequence currentText = node.getText();
        if (!text.equals(currentText)) {
            ...
            if (!node.performAction(AccessibilityNodeInfo.ACTION_SET_SELECTION, args) &&
                    currentText.length() > 0) {
                // TODO: Decide if we should throw here
                Log.w(TAG, "AccessibilityNodeInfo#performAction(ACTION_SET_SELECTION) failed");
            }
node.getText() is returning null and currentText is null , and "currentText.length()" is causing the app to crash.

**Comment by prabintim** [comment]
Was it ever solved? I am seeing the exact same issue with API 18 where my EditText is inside TextInputLayout.
