### ISSUE TITLE
IntentsBasicSample - All Instrumentation Tests Fail

### ISSUE THREAD

**Issue by mrk-han** [googlesamples/android-testing#220]
When running the tests in IntentsBasicSample under androidTest, all are failing with this stacktrace.

I ran the BasicSample tests which ran fine, then imported the build.gradle from IntentsBasicSample and found these tests are failing.

Let me know if I can provide any additional information that could be useful. Thanks!

```
java.lang.RuntimeException: java.lang.NoSuchFieldException: INJECT_INPUT_EVENT_MODE_ASYNC
at androidx.test.espresso.base.InputManagerEventInjectionStrategy.initialize(InputManagerEventInjectionStrategy.java:105)
at androidx.test.espresso.base.BaseLayerModule.provideEventInjector(BaseLayerModule.java:132)
at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.proxyProvideEventInjector(BaseLayerModule_ProvideEventInjectorFactory.java:30)
at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.provideInstance(BaseLayerModule_ProvideEventInjectorFactory.java:21)
at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:17)
at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:7)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:51)
at androidx.test.espresso.base.UiControllerImpl_Factory.provideInstance(UiControllerImpl_Factory.java:57)
at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:40)
at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:8)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:51)
at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.provideInstance(UiControllerModule_ProvideUiControllerFactory.java:28)
at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:23)
at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:9)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:51)
at androidx.test.espresso.DaggerBaseLayerComponent$ViewInteractionComponentImpl.viewInteraction(DaggerBaseLayerComponent.java:271)
at androidx.test.espresso.Espresso.onView(Espresso.java:75)
at com.example.android.testing.espresso.BasicSample.DialerActivityTest.typeNumber_ValidInput_InitiatesCall_truth(DialerActivityTest.java:130)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2136)
Caused by: java.lang.NoSuchFieldException: INJECT_INPUT_EVENT_MODE_ASYNC
at java.lang.Class.getField(Class.java:1601)
at androidx.test.espresso.base.InputManagerEventInjectionStrategy.initialize(InputManagerEventInjectionStrategy.java:89)
... 48 more
```

**Comment by mrk-han** [comment]
Issue was resolved after installing new Emulator and running tests from command line. Not sure which actually corrected the issue.

**Comment by donce** [comment]
I had the same annoying issue when migrating to AndroidX - the only solution which worked for me was to use **Android 9 Pie** instead of **Android P** emulated image.
