### ISSUE TITLE
Bazel CI: Failing with Bazel on HEAD

### ISSUE THREAD

**Issue by jin** [googlesamples/android-testing#224]
See builds at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/628

It's passing with stable Bazel 0.19.2 though: https://buildkite.com/bazel/android-testing

**Comment by meteorcloudy** [comment]
@jin If you don't know which change caused this failure, maybe https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#culprit-finder can help ;)

**Comment by jin** [comment]
@meteorcloudy great idea! let me try that.

**Comment by meteorcloudy** [comment]
@jin, Looks like the Bazel artifact for 63453bdbc6b05bd201375ee9e25b35010ae88aab got deleted.
I just found out we have a 30 days life cycle for our GCS bucket (`bazel-builds`)

**Comment by meteorcloudy** [comment]
Just removed the 30 days life cycle rule, but you'll have to find a green commit within the recent 30 days.

**Comment by jin** [comment]
thanks for spotting that, was wondering why the artifacts weren't found. finding a green commit now..

**Comment by jin** [comment]
0.20.0rc4 doesn't work, but 0.19.2 does. continuing with the bisect.

also for posterity: git is pretty smart at checking out to a certain day:

```
git checkout @{yesterday}
git checkout @{2.days.ago}
git checkout @{'2 days ago'}
git checkout @{'5 minutes ago'}
git checkout @{'1 month 2 weeks 3 days 1 hour 1 second ago'}
git checkout any-branch-name@{'1 hour ago'}
```

https://stackoverflow.com/questions/4052854/how-do-i-check-out-what-was-in-my-git-repository-n-days-ago/4052884

**Comment by meteorcloudy** [comment]
Wow, cool!

**Comment by jin** [comment]
looks like it started failing >30 days ago, I will do a local bisect.

**Comment by jin** [comment]
found the commit: https://github.com/bazelbuild/bazel/commit/e2649cf4ee2d08ec803478650c20f8caa87ec440

this actually makes the rule more correct, so the underlying projects need to change. I'll look into this more.

**Comment by jin** [comment]
Looks like Bazel's zip filtering filtered a core desugar class out:

```
11-29 20:03:58.729  2599  2612 I MonitoringInstr: Setting context classloader to 'dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk", zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.android.testing.espresso.BasicSample-2, /data/app-lib/com.example.android.testing.espresso.BasicSample-2, /system/lib]]]', Original: 'dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk", zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.android.testing.espresso.BasicSample-2, /data/app-lib/com.example.android.testing.espresso.BasicSample-2, /system/lib]]]'
11-29 20:03:58.729  2599  2612 I UsageTrackerFacilitator: Usage tracking disabled
11-29 20:03:58.739  2599  2612 I TestRunner: run started: 1 tests
11-29 20:03:58.739  2599  2612 I TestRunner: started: changeText_sameActivity(com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest)
11-29 20:03:58.739  2599  2599 I MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
11-29 20:03:58.739  2599  2612 E TestRunner: failed: changeText_sameActivity(com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest)
11-29 20:03:58.739  2599  2612 E TestRunner: ----- begin exception -----
11-29 20:03:58.739  2599  2612 I TestRunner: finished: changeText_sameActivity(com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest)
11-29 20:03:58.749  2599  2599 I MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
11-29 20:03:58.749  2599  2612 E TestRunner: failed: com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest
11-29 20:03:58.749  2599  2612 E TestRunner: ----- begin exception -----
11-29 20:03:58.749  2599  2612 E TestRunner: failed: null
11-29 20:03:58.749  2599  2612 E TestRunner: ----- begin exception -----
11-29 20:03:58.749  2599  2612 E TestExecutor: Fatal exception when running tests
11-29 20:03:58.749  2599  2612 E TestExecutor: java.lang.NoClassDefFoundError: com/google/devtools/build/android/desugar/runtime/ThrowableExtension
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.Failure.getTrace(Failure.java:75)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at androidx.test.internal.runner.listener.LogRunListener.testFailure(LogRunListener.java:63)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
11-29 20:03:58.749  2599  2612 E TestExecutor: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.devtools.build.android.desugar.runtime.ThrowableExtension" on path: DexPathList[[zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk", zip file "/data/app/com.example.android.testing.espresso.BasicSample-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.android.testing.espresso.BasicSample-2, /data/app-lib/com.example.android.testing.espresso.BasicSample-2, /system/lib]]
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
11-29 20:03:58.749  2599  2612 E TestExecutor: 	... 14 more
11-29 20:03:58.749  2599  2599 I MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
11-29 20:03:58.749  2599  2612 I MonitoringInstr: waitForActivitiesToComplete() took: 0ms
11-29 20:03:58.959  1593  1719 I am_kill : [0,2599,com.example.android.testing.espresso.BasicSample,0,stop com.example.android.testing.espresso.BasicSample]
11-29 20:03:58.959  2569  2585 I OrchestrationXmlTestRunListener: Created xml report file at /storage/sdcard/odo/test_result_-431479683.xml
11-29 20:03:58.959  2569  2585 I OrchestrationXmlTestRunListener: XML test result file generated at /storage/sdcard/odo/test_result_-431479683.xml. Total tests 1, failure 1, 
11-29 20:03:58.959  1593  1719 I ActivityManager: Force stopping com.example.android.testing.espresso.BasicSample appid=10053 user=0: finished inst
11-29 20:03:58.959  1593  1719 I ActivityManager: Killing 2599:com.example.android.testing.espresso.BasicSample/u0a53 (adj 0): stop com.example.android.testing.espresso.BasicSample
```

cc @ahumesky
