### ISSUE TITLE
Android Testing broken with Bazel at HEAD

### ISSUE THREAD

**Issue by buchgr** [googlesamples/android-testing#250]
```
INFO: SHA256 (https://github.com/bazelbuild/gmaven_rules/archive/20181206-1.tar.gz) = 224d90fce797ed63e6ebf3cf3658b721ce2c4b2d601d875f57339e93d144f9ef
--
  | ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': java.io.IOException: Error extracting /home/bazel/.cache/bazel/_bazel_bazel/d418520e54361cd6e00ea149f1dd864f/external/gmaven_rules/20181206-1.tar.gz to /home/bazel/.cache/bazel/_bazel_bazel/d418520e54361cd6e00ea149f1dd864f/external/gmaven_rules: Prefix "gmaven_rules-20181206-1" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_jvm_external-20181206-1".
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/855#cfdcd538-4f39-4051-9aba-df66365c855a

**Comment by jin** [comment]
Thanks! This particular error is now fixed upstream. We're now seeing another error:

```
ERROR: D:/b/fwx2n6bg/external/bazel_tools/src/main/native/windows/BUILD:60:1: Couldn't build file external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/processes-jni.obj: undeclared inclusion(s) in rule '@bazel_tools//src/main/native/windows:windows_jni.dll':
--
  | this rule is missing dependency declarations for the following files included by 'external/bazel_tools/src/main/native/windows/processes-jni.cc':
  | 'D:/b/gcs55fj7/execroot/rules_jvm_external/bazel-out/host/genfiles/external/bazel_tools/src/main/native/jni_md.h'
  | ERROR: D:/b/fwx2n6bg/external/bazel_tools/src/main/native/windows/BUILD:60:1: Couldn't build file external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/jni-util.obj: undeclared inclusion(s) in rule '@bazel_tools//src/main/native/windows:windows_jni.dll':
  | this rule is missing dependency declarations for the following files included by 'external/bazel_tools/src/main/native/windows/jni-util.cc':
  | 'D:/b/gcs55fj7/execroot/rules_jvm_external/bazel-out/host/genfiles/external/bazel_tools/src/main/native/jni_md.h'
  | ERROR: D:/b/fwx2n6bg/external/bazel_tools/src/main/native/windows/BUILD:60:1: Couldn't build file external/bazel_tools/src/main/native/windows/_objs/windows_jni.dll/file-jni.obj: undeclared inclusion(s) in rule '@bazel_tools//src/main/native/windows:windows_jni.dll':
  | this rule is missing dependency declarations for the following files included by 'external/bazel_tools/src/main/native/windows/file-jni.cc':
  | 'D:/b/gcs55fj7/execroot/rules_jvm_external/bazel-out/host/genfiles/external/bazel_tools/src/main/native/jni_md.h'
```

I'm not sure what this is. Let's see what tonight's downstream run says.

**Comment by jin** [comment]
Should be fixed by https://github.com/googlesamples/android-testing/pull/251

**Comment by jin** [comment]
There seems to be issues with rules_jvm_external on the Buildkite Windows CI in its JSON parsing:

```

ERROR: D:/b/bk-windows-java8-mmxz/bazel/android-testing/ui/espresso/IntentsBasicSample/BUILD.bazel:30:1: no such package '@maven//': Traceback (most recent call last):
--
  | File "D:/b/moh4wxcp/external/rules_jvm_external/coursier.bzl", line 335
  | json_parse(_cat_file(repository_ctx, "dep-t..."))
  | File "D:/b/moh4wxcp/external/rules_jvm_external/third_party/bazel_json/lib/json_parser.bzl", line 667, in json_parse
  | fail(("parsing JSON failed:\n%s\n\npa...)))
  | parsing JSON failed:
  | invalid action: -1  on input 'C'
  |  
  | parser:
  | {"rejected": True, "rejected_reason": "invalid action: -1  on input 'C'", "max_depth": 20, "mode_stack": [0], "top": 0, "state": 0, "state_chars": None, "reduction_stack": [[]], "reduction_hooks": {"entry_key": <function _reduce_literal from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "entry_value": <function _reduce_literal from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "object": <function _reduce_object from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "array": <function _reduce_array from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>}, "tokenizer_hooks": {"string": <function _tokenize_string from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "integer": <function _tokenize_int from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "null": <function _tokenize_null from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "true": <function _tokenize_true from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>, "false": <function _tokenize_false from @rules_jvm_external//third_party/bazel_json/lib:json_parser.bzl>}, "hacky_treatment_unknown_chars_as_etc": True, "_DEBUG": False} and referenced by


```
I don't see these issues on my local Windows machine.

I'll disable them until we figure out where this issue comes from.

**Comment by jin** [comment]
This is now fixed
