### ISSUE TITLE
Run individual test from Android Studio

### ISSUE THREAD

**Issue by bootstraponline** [googlesamples/android-testing#6]
Is there a way to run an individual test from [Android Studio](http://stackoverflow.com/questions/2422378/intellij-idea-with-junit-4-7-junit-version-3-8-or-later-expected)? With the default config in this repo for the BasicSample, I see this error:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/Android Studio.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/Android Studio.app/Contents/lib/idea_rt.jar:/Applications/Android Studio.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/user/woven/android-sdk-macosx/platforms/android-21/android.jar:/Users/user/woven/android-sdk-macosx/platforms/android-21/data/res:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/classes/debug:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test/testing-support-lib/0.1/classes.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test/testing-support-lib/0.1/res:/Users/user/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/user/.gradle/caches/modules-2/files-2.1/com.squareup/javawriter/2.1.1/67ff45d9ae02e583d0f9b3432a5ebbe05c30c966/javawriter-2.1.1.jar:/Users/user/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.2/479c1e06db31c432330183f5cae684163f186146/javax.annotation-api-1.2.jar:/Users/user/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/user/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/18.0/cce0823396aa693798f8882e64213b1772032b09/guava-18.0.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test.espresso/espresso-idling-resource/2.0/classes.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test.espresso/espresso-idling-resource/2.0/res:/Users/user/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-library/1.1/b988c01468e3398d46678a2eb48aeb5bde271e9f/hamcrest-library-1.1.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/libs/droiddriver.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test.espresso/espresso-core/2.0/classes.jar:/Users/user/woven/espresso_samples/espresso/BasicSample/app/build/intermediates/exploded-aar/com.android.support.test.espresso/espresso-core/2.0/res:/Users/user/woven/android-sdk-macosx/extras/android/m2repository/com/android/support/support-annotations/21.0.3/support-annotations-21.0.3.jar:/Users/user/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/2.0.1/516c03b21d50a644d538de0f0369c620989cd8f0/jsr305-2.0.1.jar:/Users/user/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/Users/user/.gradle/caches/modules-2/files-2.1/junit/junit-dep/4.10/64417b3bafdecd366afa514bd5beeae6c1f85ece/junit-dep-4.10.jar:/Users/user/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-integration/1.1/8d47177aa4da0f259fc823a39736bad2f09993d5/hamcrest-integration-1.1.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest
!!! JUnit version 3.8 or later expected:

java.lang.RuntimeException: Stub!
	at junit.runner.BaseTestRunner.<init>(BaseTestRunner.java:5)
	at junit.textui.TestRunner.<init>(TestRunner.java:54)
	at junit.textui.TestRunner.<init>(TestRunner.java:48)
	at junit.textui.TestRunner.<init>(TestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.junitVersionChecks(JUnitStarter.java:190)
	at com.intellij.rt.execution.junit.JUnitStarter.canWorkWithJUnitVersion(JUnitStarter.java:173)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

I found [this plugin](https://github.com/evant/android-studio-unit-test-plugin), I'm not sure if there's a better way.

**Comment by bootstraponline** [comment]
I figured it out: 

![run_one_test](https://cloud.githubusercontent.com/assets/1173057/6003549/9bfd1c12-aaca-11e4-91a4-3b6e34549dab.png)

Android Studio works properly, just have to press the right button.

**Comment by ishawnthye** [comment]
Why i don't see this option available @@

**Comment by dpkirchner** [comment]
@bootstraponline could you share how and where you found that view?

**Comment by bootstraponline** [comment]
> @bootstraponline could you share how and where you found that view?

I right clicked on the test method body.
