### ISSUE TITLE
onWebView Element is not currently interactable and may not be manipulated

### ISSUE THREAD

**Issue by neal1231990511** [googlesamples/android-testing#61]
when I use espresso onWebView to click html button it will fail.

Some tests WebView components of layout xml :

PASS   :    android:layout_width="wrap_content"
                  android:layout_height="match_parent"
                  android:id="@+id/webView"
                 
PASS   :    android:layout_width="wrap_content"
                  android:layout_height="10dp"
                  android:id="@+id/webView"
                 
PASS   :    android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:id="@+id/webView"
                

FAIL    :     android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:id="@+id/webView"
                 
FAIL    :     android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:id="@+id/webView"
                 
FAIL    :     android:layout_width="100dp"
                  android:layout_height="wrap_content"
                  android:id="@+id/webView"
                
I found if the layout_height of WebView is " wrap_content " will run fail and got error message.

error message:
java.lang.RuntimeException: java.lang.RuntimeException: Error in evaluationEvaluation: status: 12 value: {message=Element is not currently interactable and may not be manipulated} hasMessage: true message: Element is not currently interactable and may not be manipulated
at android.support.test.espresso.web.sugar.Web$WebInteraction$ExceptionPropagator.<init>(Web.java:323)
at android.support.test.espresso.web.sugar.Web$WebInteraction.doEval(Web.java:292)
at android.support.test.espresso.web.sugar.Web$WebInteraction.perform(Web.java:259)
at com.example.cake.cake_esp_test.WebActivityTest.enter_email_and_password_submit(WebActivityTest.java:54)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.RuntimeException: Error in evaluationEvaluation: status: 12 value: {message=Element is not currently interactable and may not be manipulated} hasMessage: true message: Element is not currently interactable and may not be manipulated
at android.support.test.espresso.web.model.SimpleAtom.handleBadEvaluation(SimpleAtom.java:142)
at android.support.test.espresso.web.model.SimpleAtom.transform(SimpleAtom.java:76)
at android.support.test.espresso.web.model.SimpleAtom.transform(SimpleAtom.java:30)
at android.support.test.espresso.web.action.AtomAction$2.apply(AtomAction.java:136)
at android.support.test.espresso.web.action.AtomAction$2.apply(AtomAction.java:133)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$2.apply(Futures.java:760)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
at android.support.test.espresso.web.deps.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at android.support.test.espresso.web.deps.guava.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at android.support.test.espresso.web.deps.guava.util.concurrent.SettableFuture.set(SettableFuture.java:53)
at android.support.test.espresso.web.action.AtomAction$1.run(AtomAction.java:117)
at android.support.test.espresso.web.deps.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at android.support.test.espresso.web.deps.guava.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918)
at android.support.test.espresso.web.deps.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:914)
at android.support.test.espresso.web.deps.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at android.support.test.espresso.web.deps.guava.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at android.support.test.espresso.web.deps.guava.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918)
at android.support.test.espresso.web.deps.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at android.support.test.espresso.web.deps.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at android.support.test.espresso.web.deps.guava.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
at android.support.test.espresso.web.action.JavascriptEvaluation$ValueCallbackFuture.onReceiveValue(JavascriptEvaluation.java:429)
at com.android.org.chromium.android_webview.AwContents$5.handleJavaScriptResult(AwContents.java:1738)
at com.android.org.chromium.content.browser.webcontents.WebContentsImpl.onEvaluateJavaScriptResult(WebContentsImpl.java:227)
at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by JoseAlcerreca** [comment]
Is this related to the WebView sample? Please re-open in that case.

**Comment by ssoumya** [comment]
Is anybody resolved above webview issue[ "status: 12 value: {message=Element is not currently interactable and may not be manipulated.]?. 
Webview height is set to match_parent still getting above error .

**Comment by nabinkhadka** [comment]
Mine worked when I set my webview's height to match_parent. Thank you 👍
