### ISSUE TITLE
Running tests on a KitKat device from command line

### ISSUE THREAD

**Issue by shauvik** [googlesamples/android-testing#7]
Hi,

Can these sample expresso tests be run on KitKat?
These are the errors i receive when testing on my LG phone running Kitkat.

```
MacBookPro:android-testing shauvik$ ./gradlew connectedCheck
:espresso:BasicSample:app:preBuild
:espresso:BasicSample:app:compileDebugNdk UP-TO-DATE
:espresso:BasicSample:app:preDebugBuild
:espresso:BasicSample:app:checkDebugManifest
:espresso:BasicSample:app:prepareDebugDependencies
:espresso:BasicSample:app:compileDebugAidl UP-TO-DATE
:espresso:BasicSample:app:compileDebugRenderscript UP-TO-DATE
:espresso:BasicSample:app:generateDebugBuildConfig UP-TO-DATE
:espresso:BasicSample:app:generateDebugAssets UP-TO-DATE
:espresso:BasicSample:app:mergeDebugAssets UP-TO-DATE
:espresso:BasicSample:app:generateDebugResValues UP-TO-DATE
:espresso:BasicSample:app:generateDebugResources UP-TO-DATE
:espresso:BasicSample:app:mergeDebugResources UP-TO-DATE
:espresso:BasicSample:app:processDebugManifest UP-TO-DATE
:espresso:BasicSample:app:processDebugResources UP-TO-DATE
:espresso:BasicSample:app:generateDebugSources UP-TO-DATE
:espresso:BasicSample:app:compileDebugJava UP-TO-DATE
:espresso:BasicSample:app:preDexDebug UP-TO-DATE
:espresso:BasicSample:app:dexDebug UP-TO-DATE
:espresso:BasicSample:app:processDebugJavaRes UP-TO-DATE
:espresso:BasicSample:app:validateDebugSigning
:espresso:BasicSample:app:packageDebug UP-TO-DATE
:espresso:BasicSample:app:zipalignDebug UP-TO-DATE
:espresso:BasicSample:app:assembleDebug UP-TO-DATE
:espresso:BasicSample:app:compileDebugTestNdk UP-TO-DATE
:espresso:BasicSample:app:preDebugTestBuild
:espresso:BasicSample:app:prepareComAndroidSupportTestEspressoEspressoCore20Library UP-TO-DATE
:espresso:BasicSample:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource20Library UP-TO-DATE
:espresso:BasicSample:app:prepareComAndroidSupportTestTestingSupportLib01Library UP-TO-DATE
:espresso:BasicSample:app:prepareDebugTestDependencies
:espresso:BasicSample:app:compileDebugTestAidl UP-TO-DATE
:espresso:BasicSample:app:processDebugTestManifest UP-TO-DATE
:espresso:BasicSample:app:compileDebugTestRenderscript UP-TO-DATE
:espresso:BasicSample:app:generateDebugTestBuildConfig UP-TO-DATE
:espresso:BasicSample:app:generateDebugTestAssets UP-TO-DATE
:espresso:BasicSample:app:mergeDebugTestAssets UP-TO-DATE
:espresso:BasicSample:app:generateDebugTestResValues UP-TO-DATE
:espresso:BasicSample:app:generateDebugTestResources UP-TO-DATE
:espresso:BasicSample:app:mergeDebugTestResources UP-TO-DATE
:espresso:BasicSample:app:processDebugTestResources UP-TO-DATE
:espresso:BasicSample:app:generateDebugTestSources UP-TO-DATE
:espresso:BasicSample:app:compileDebugTestJava UP-TO-DATE
:espresso:BasicSample:app:preDexDebugTest UP-TO-DATE
:espresso:BasicSample:app:dexDebugTest UP-TO-DATE
:espresso:BasicSample:app:processDebugTestJavaRes UP-TO-DATE
:espresso:BasicSample:app:packageDebugTest UP-TO-DATE
:espresso:BasicSample:app:assembleDebugTest UP-TO-DATE
:espresso:BasicSample:app:connectedAndroidTest
Tests on LG-D855 - 4.4.2 failed: Unable to find instrumentation info for: ComponentInfo{com.example.android.testing.espresso.BasicSample.test/android.support.test.runner.AndroidJUnitRunner}

com.android.builder.testing.ConnectedDevice > hasTests[LG-D855 - 4.4.2] FAILED
No tests found.
:espresso:BasicSample:app:connectedAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':espresso:BasicSample:app:connectedAndroidTest'.
> There were failing tests. See the report at: file:///Users/shauvik/Projects/android-testing/espresso/BasicSample/app/build/outputs/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.487 secs
MacBookPro:android-testing shauvik$ 
```

**Comment by shauvik** [comment]
On passing the --stacktrace option, It complains about missing activity. Any ideas?

```
com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest > testChangeText_newActivity[LG-D855 - 4.4.2] FAILED
	android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)

com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest > testChangeText_sameActivity[LG-D855 - 4.4.2] FAILED
	android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
:espresso:BasicSample:app:connectedAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':espresso:BasicSample:app:connectedAndroidTest'.
> There were failing tests. See the report at: file:///Users/shauvik/Projects/android-testing/espresso/BasicSample/app/build/outputs/reports/androidTests/connected/index.html

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':espresso:BasicSample:app:connectedAndroidTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///Users/shauvik/Projects/android-testing/espresso/BasicSample/app/build/outputs/reports/androidTests/connected/index.html
	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.runTests(DeviceProviderInstrumentTestTask.groovy:107)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more


BUILD FAILED

Total time: 1 mins 37.412 secs
```

**Comment by JoseAlcerreca** [comment]
Did you disable animations?

**Comment by otw** [comment]
Can you please open up the test report: file:///Users/shauvik/Projects/android-testing/espresso/BasicSample/app/build/outputs/reports/androidTests/connected/index.html and post the contents here? With the above it is hard to actually nail down the error.

**Comment by shauvik** [comment]
@JoseAlcerreca @otw 
Thanks for the tip. It works after I turn off all animations.
http://lifehacker.com/disable-animations-on-android-to-improve-performance-1583554900
