### ISSUE TITLE
WebBasicSample fails at least on 4.0.4, 5.1.1 

### ISSUE THREAD

**Issue by JoseAlcerreca** [googlesamples/android-testing#73]
Galaxy Nexus 4.0.4

```
com.example.android.testing.espresso.web.BasicSample.WebViewActivityTest > typeTextInInput_clickButton_SubmitsForm[Galaxy Nexus - 4.0.4] FAILED 
	java.lang.RuntimeException: java.lang.RuntimeException: Atom evaluation returned null!
	at android.support.test.espresso.web.sugar.Web$WebInteraction$ExceptionPropagator.<init>(Web.java:323)
:app:connectedDebugAndroidTest FAILED
```

----
OnePlusOne 5.1.1
```
com.example.android.testing.espresso.web.BasicSample.WebViewActivityTest > typeTextInInput_clickButton_SubmitsForm[A0001 - 5.1.1] FAILED 
	java.lang.RuntimeException: java.lang.RuntimeException: Atom evaluation returned null!
	at android.support.test.espresso.web.sugar.Web$WebInteraction$ExceptionPropagator.<init>(Web.java:323)
:app:connectedDebugAndroidTest FAILED
```

**Comment by JoseAlcerreca** [comment]
Fixed in https://github.com/googlesamples/android-testing/commit/009bd2c33fd9e534d219d3f6464ed84093d3ae82
